stages:
    - build
    - test

cache:
    paths:
        - node_modules/
    
build:
    stage: build
    script:
        - npm install
        - npm run build
    artifacts:
        paths:
            - node_modules/
            - .next/

test:
    stage: test
    script:
        - npm run test